# Generated by Django 5.1.2 on 2024-10-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='categoryId',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='note',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='effectType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredientKr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
