# Generated by Django 5.1.2 on 2024-10-17 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pregnancy_date',
            new_name='pregnancyDate',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_type',
            new_name='userType',
        ),
    ]
