# Generated by Django 5.1.2 on 2024-11-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_pregnancy_date_profile_pregnancydate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pregnancyWeek',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pregnancyDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
